FIX: filter conditionally excluded fields from wizard submission
paviliondev/discourse-custom-wizard pull request #109
Opened 2021-05-05 07:43 UTC by fzngagan

2021-05-07 05:08 UTC, angusmcleod requested changes
This looks good, but I do think we need at least two seperate tests there, rather than one big test for multiple cases.

2021-05-07 05:08 UTC, angusmcleod commented on spec/requests/custom_wizard/steps_controller_spec.rb
> +    put '/w/super-mega-fun-wizard/steps/step_2.json', params: {
@fzngagan We need to break this up into two seperate tests.

2021-05-07 08:14 UTC, fzngagan commented
@angusmcleod 
My thinking is, we are testing exclusion here. So we need to confirm both inclusion and then exclusion.

2021-05-10 08:55 UTC, fzngagan commented
Conclusion from the discussion.
re-submitting step 1, should get rid of the submission from step 2. Investigate why that's not the case.

2021-05-12 13:31 UTC, fzngagan commented
@angusmcleod 
The issue was, that filtering needs to happen when the wizard is built **post submission being saved**. I've also simplified the spec.

2021-05-13 20:44 UTC, angusmcleod approved these changes

2021-05-13 20:44 UTC, merged