FIX: clear submission if skipped by user
paviliondev/discourse-custom-wizard pull request #138
Opened 2021-08-10 09:02 UTC by fzngagan

2021-08-16 02:53 UTC, angusmcleod requested changes

2021-08-16 02:53 UTC, angusmcleod commented on lib/custom_wizard/submission.rb
> +  def self.remove(submission)
@fzngagan When you're passing an entire instance as the argument it's a sign that tthis should be an instance method, and the class method should be the alias method.

2021-08-22 21:36 UTC, fzngagan commented
@angusmcleod I've made the change.

One thing I've done here is to use the `@` notation to access instance variables. IMHO, taking advantage of `attr_accessor` is more suitable when accessing stuff outside the class context. In the class context, it hinders readibility a little bit in many cases. Thoughts?

2021-08-23 04:33 UTC, angusmcleod requested changes

2021-08-23 04:33 UTC, angusmcleod commented on lib/custom_wizard/submission.rb
> +  def self.remove(submission)
@fzngagan I'm not sure this class method makes sense now. We should just have the instance method.

2021-08-23 06:12 UTC, merged