FIX: grant reply/edit permissions to topic author
paviliondev/discourse-custom-wizard pull request #151
Opened 2021-10-19 03:37 UTC by fzngagan

2021-10-21 06:12 UTC, angusmcleod requested changes

2021-10-21 06:12 UTC, angusmcleod commented on lib/custom_wizard/action.rb
> +          wizard_created: @wizard.id,
@fzngagan Should be ``wizard_id``

2021-10-21 06:12 UTC, angusmcleod commented on lib/custom_wizard/action.rb
> +          wizard_submission: @wizard.current_submission.id
@fzngagan Should be ``wizard_submission_id``

2021-10-21 06:12 UTC, angusmcleod commented on plugin.rb
> +  add_to_class(:topic, :wizard_created) do
@fzngagan Update names as per above

2021-11-02 08:07 UTC, fzngagan commented on extensions/guardian.rb
> +  def wizard_can_create_topic_on_category?(wizard, topic)
@angusmcleod 
What if the given wizard can no longer create topics?

2021-11-02 08:07 UTC, fzngagan commented on extensions/guardian.rb
> +    submission_data = begin
Sure, will make that change.

2021-11-02 08:09 UTC, fzngagan commented on spec/extensions/guardian_extension_spec.rb
> +      expect(user.guardian.send(:wizard_user_can_create_topic_on_category?, topic)).to be_truthy
The problem here is, the Rspec config in discourse is quite lax so the `can_create_topic?` and similar methods mostly return true so can't rely on testing them.

2021-11-02 08:11 UTC, fzngagan commented on extensions/guardian.rb
> +  def wizard_can_create_topic_on_category?(wizard, topic)
Or say, what if the user no longer has access to the wizard.

2021-12-08 07:58 UTC, fzngagan commented
New Spec:
If user already has `reply & see` permissions and the topic is created via a wizard, grant the user edit rights.

2022-01-31 08:03 UTC, angusmcleod approved these changes
@fzngagan Looks good :+1:

2022-01-31 08:04 UTC, merged