FEATURE: switch to using subscription gem to avoid the need to rely on Subscription Client plugin
paviliondev/discourse-custom-wizard pull request #266
Opened 2023-09-08 06:25 UTC by merefield

2023-09-28 11:20 UTC, merefield commented
@angusmcleod remaining failing tests are not related to this PR and are also failing in Production.  I've not tackled them because they are out of scope.

2023-09-28 11:55 UTC, angusmcleod commented
@merefield Nice. Ping me when it's ready for review.

2023-11-15 17:12 UTC, merefield commented
@angusmcleod, these front end tests are not failing locally on two types of browser, any ideas?

2023-11-15 20:00 UTC, angusmcleod commented
Not sure.

@jumagura Any idea why these tests are failing?

2023-11-16 18:00 UTC, merefield commented
@jumagura please ignore, I found the problem, it's a breaking change from core due to updates to Composer and Modal selectors.

@angusmcleod this is now ready for review and merge.

2023-11-17 08:03 UTC, angusmcleod requested changes
@merefield Two minor changes and a comment for future reference (no need to convert to .gjs in this PR).

2023-11-17 08:06 UTC, merefield commented on assets/javascripts/discourse/components/wizard-subscription-badge.hbs
> +  <svg
can do ... I just re-used what was there already.  I'll address.

2023-11-17 09:12 UTC, merefield commented on assets/javascripts/discourse/components/wizard-subscription-badge.hbs
> +  <svg
this is both resolved and improved

2023-11-17 09:13 UTC, merefield commented on assets/javascripts/discourse/components/wizard-subscription-cta.js
> +import { inject as service } from "@ember/service";
Glimmer split was all the rage only a few weeks ago ... can't keep up!

2023-11-17 09:13 UTC, merefield commented on lib/custom_wizard/subscription.rb
> -  def self.client_installed?
this is restored ... please check it's enough @angusmcleod

2023-11-17 09:14 UTC, merefield commented
all requested changes implemented @angusmcleod ...

2023-11-17 09:38 UTC, angusmcleod commented
@merefield Looks like we've got a failing check here.

2023-11-17 10:04 UTC, merefield commented
resolved @angusmcleod

2023-11-17 13:03 UTC, angusmcleod approved these changes

2023-11-17 13:03 UTC, merged