COMPATIBILITY: Add this to avoid deprecation
paviliondev/discourse-custom-wizard pull request #267
Opened 2023-09-14 13:06 UTC by merefield

2023-09-14 22:06 UTC, angusmcleod requested changes
@merefield Just one very minor change and I'll merge.

2023-09-14 22:06 UTC, angusmcleod commented on assets/javascripts/discourse/controllers/admin-wizards-wizard-show.js.es6
> +      // controller.setup();
@merefield minor, but please don't leave commented out code. Either remove or integrate.

2023-09-15 06:05 UTC, merefield commented
@angusmcleod resolved, apologies for that, unintentional.

2023-09-15 06:55 UTC, angusmcleod approved these changes

2023-09-15 06:55 UTC, merged