FEATURE: text length counter for text type fields
paviliondev/discourse-custom-wizard pull request #65
Opened 2021-01-08 06:52 UTC by fzngagan

- Text length counter for all text type fields i.e. text, textarea, composer

2021-01-14 05:55 UTC, angusmcleod requested changes
@fzngagan Mostly there, but note that you've missed off the last part of the spec

> The character counter should include the max characters setting for that field, if it has been set. In the format current/max.

Make sure you always double check the spec.

A few minor code issues as well.

2021-01-14 05:55 UTC, angusmcleod commented on assets/javascripts/wizard/initializers/custom-wizard-field.js.es6
> +      textType: function() {
@fzngagan We don't use this old style of computed property. I know that the other code in this file does, but we should use the new approach when writing new code.

2021-01-14 05:55 UTC, angusmcleod commented on assets/javascripts/wizard/templates/components/wizard-field.hbs
> +{{#if field.char_counter}}
@fzngagan This should be inside the input aread so that the counter can sit in-line with any input controls, like the toggle preview button.

2021-01-14 05:55 UTC, angusmcleod commented on assets/stylesheets/wizard/custom/base.scss
> +  font-weight: bold;
@fzngagan No need for this to be bold. Users can bold it in a theme if they wish.

2021-01-20 07:18 UTC, angusmcleod commented
@fzngagan We need to close this one. How are you going on it?

2021-01-20 07:20 UTC, fzngagan commented
@angusmcleod 
I already nudged you to take a look. But now I see a conflict.

2021-01-20 08:58 UTC, angusmcleod approved these changes

2021-01-20 08:59 UTC, merged